### ISSUE TITLE
There were headers present in the request which were not signed

### ISSUE THREAD

**Issue by charlesvinette** [JustinM1/VaporS3Signer#2] opened 2017-01-13 07:48 UTC
Hi, thanks for your work on this package.

I am trying to fetch a presigned URL from S3 for a bucket of mine. However, when I use the package and send the request, I am getting this message: "There were headers present in the request which were not signed".

Any idea? Here is the code.

```swift
guard let presignedURL = try drop.s3Signer?.presignedURLV4(httpMethod: .get, urlString: "https://s3.amazonaws.com/ecoroundgg/testUploadImage.png", expiration: TimeFromNow.thirtyMinutes, headers: [:]), let url = URL(string: presignedURL.urlString) else { throw Abort.serverError }
    
    _ = URLRequest(url:url)
    var headerToSend = [HeaderKey:String]()
    for header in presignedURL.headers{
      headerToSend[HeaderKey(header.key)] = header.value
    }
    print(headerToSend)
    let res = try drop.client.get(url.absoluteString, headers:headerToSend)
    print(res)
    return res
  }
```

**Comment by JustinM1** [comment] 2017-01-14 00:27
I'll look into it this weekend. In the meantime, you can use v2 pre-signed url or if your doing the entire request in one spot, create v4 signed headers and make the request with a regular url.

**Comment by charlesvinette** [comment] 2017-01-14 00:40
That's what I will do, thanks for your time @JustinM1 !!

**Comment by JustinM1** [comment] 2017-01-14 01:51
your welcome, let me know if you encounter any other issues.

**Comment by charlesvinette** [comment] 2017-01-14 05:56
Hey man, I am getting the same error with the v2 presigned url method. I also properly added my keys/ region in the config. Thanks for your help!

**Comment by JustinM1** [comment] 2017-01-14 06:06
Did you try making the request using URLRequest? Vapor may be adding extra headers in the request when you use the droplets client.

**Comment by charlesvinette** [comment] 2017-01-14 06:08
I double check when doing the request and nothing is added. I also tried the URL directly in the browser getting the same error. Here is my code:

```swift 
  func getS3URL(request: Request) throws -> ResponseRepresentable{
    guard let presignedURL = try drop.s3Signer?.presignedURLV4(httpMethod: .get, urlString: "https://s3.amazonaws.com/ecoroundgg/testUploadImage.png", expiration: TimeFromNow.thirtyMinutes, headers: [:]), let url = URL(string: presignedURL.urlString) else { throw Abort.serverError }
    
    _ = URLRequest(url:url)
    var headerToSend = [HeaderKey:String]()
    for header in presignedURL.headers{
      headerToSend[HeaderKey(header.key)] = header.value
    }
    print(url.absoluteString)
    let res = try drop.client.get(url.absoluteString, headers:headerToSend)
    print(res)
    return res
  }
```

**Comment by JustinM1** [comment] 2017-01-14 06:23
this worked for v2
`let urlString = "https://" + Region.usEast1_Virginia.host.appending("/TESTURL.png")`
`let preSignedURL = try self.drop.s3Signer?.presignedURLV2(urlString: urlString, expiration: TimeFromNow.thirtyMinutes)`

Response
- HTTP/1.1 200 OK
- Headers:
	Last-Modified: Tue, 27 Dec 2016 22:26:25 GMT
	Accept-Ranges: bytes
	ETag: "2141d1796406c547deda83ac6ae4293d"
	Server: AmazonS3
/+caAzUaw2iXJjer4X04JJwtA7MDgh4=
	x-amz-request-id: 63DDAB0D65201C1E
	Date: Sat, 14 Jan 2017 06:28:07 GMT
	Content-Type: binary/octet-stream
	Content-Length: 1059
- Body:
	PNG


I'll check the others tomorrow, what did your code for v2 look like?

**Comment by charlesvinette** [comment] 2017-01-14 06:39
Edit: In your previous example , where is the bucket name?
 Here: 
```swift
let urlString = "https://" + Region.usEast1_Virginia.host.appending("TESTURL.png")
```
Here is what I tried:

```swift
  func getS3URL(request: Request) throws -> ResponseRepresentable{
//    guard let presignedURL = try drop.s3Signer?.presignedURLV4(httpMethod: .get, urlString: "https://s3.amazonaws.com/ecoroundgg/testUploadImage.png", expiration: TimeFromNow.thirtyMinutes, headers: [:]), let url = URL(string: presignedURL.urlString) else { throw Abort.serverError }
    
    guard let presignedURL = try drop.s3Signer?.presignedURLV2(urlString: "https://s3.amazonaws.com/ecoroundgg/testupload.png", expiration: TimeFromNow.thirtyMinutes) else { throw Abort.serverError }
    
//    _ = URLRequest(url:url)
//    var headerToSend = [HeaderKey:String]()
//    for header in presignedURL.headers{
//      headerToSend[HeaderKey(header.key)] = header.value
//    }
//    print(headerToSend)
    let res = try drop.client.get(presignedURL, headers:[:])
    print(res)
    return res
  }
```

I guess at this point it has to do with my URL formatting? Probably an error on my end. Thanks for your help man.

**Comment by JustinM1** [comment] 2017-01-14 06:53
try this for your get request not that I think it makes a difference but other than that I'm out of ideas. 

`let resp = try self.drop.client.get(preSignedURL)`

If you figure out what the problem is please let me know but I don't see anything that should be giving you the header issue. I'll double check the v4 methods tomorrow and let you know if I find any issue with those.

**Comment by charlesvinette** [comment] 2017-01-14 07:10
Once again thanks for your help Justin, I just managed to make the V2 method work. Thanks a lot for your help, I had a typo in my URL. Let me know if you manage to find something wrong in V4, I took a look but didn't find anything. Thanks again and good work!!

**Comment by charlesvinette** [comment] 2017-01-14 07:42
Nope false hope... The response is: 

```
<Error>
    <Code>NoSuchKey</Code>
    <Message>The specified key does not exist.</Message>
    <Key>testfawfawf.png</Key>
    <RequestId>BD2FA384FB38CDF0</RequestId>
    <HostId>b51Diu6vjz8hMmWq3nDQvDjSdLPWMy2yJ59pSNBI0TziRKIBoHuXSiMD42qlH57viJIlWvhcb1E=</HostId>
</Error>
```
Isn't is supposed to create the URL so that I can then upload the file with the URL?

**Comment by JustinM1** [comment] 2017-01-14 08:39
I forgot but I made the v2URL get only, it's not really the most secure so it's not safe to send that type of url around with writable access. However, just until I can look more into V4 you can change the function in the source code. Go to the s3folder in your sources, click on s3SignerAWS and in the function presignedURLV2, add a param that takes an HTTP method and then in the stringToSign variable, remove "GET" and add in the HTTP method rawValue. So that way you can change it from Get to Put on an as needed basis.

**Comment by charlesvinette** [comment] 2017-01-14 18:27
Got it, I will try this solution today. Thanks again Justin!

**Comment by charlesvinette** [comment] 2017-01-15 02:53
Hey @JustinM1 , I finally found my issue. Problem was that, by using Put in the V2 method, the content type was not set in the signature so when uploading an image, it would cause an issue. I will modify the method and send in a pull request if you want :)

**Comment by JustinM1** [comment] 2017-01-17 02:48
Merged the request, thank you for your contribution!

**Closed as completed** 2017-01-17 02:48 UTC

**Comment by JustinM1** [comment] 2017-01-18 11:37
V4 pre-signed URL has been fixed. V2 Put method has been removed due to the better security associated with V4 pre-signed urls.
